[package]
name = "tree-sitter-collection"
version = "0.2.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
tree-sitter = "= 0.19.2"
tree-sitter-highlight = "0.19.2"

[build-dependencies]
cc = "1.0.54"
